FROM nginx:1.13.8

COPY ./dist /usr/share/nginx/html{{ PATH_FINAL }}

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ./nginx/enable-cross-site.conf.part /etc/nginx/conf.d/enable-cross-site.conf.part
COPY ./nginx/nginx.crt /etc/nginx/ssl/nginx.crt
COPY ./nginx/nginx.key /etc/nginx/ssl/nginx.key